empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

#se refiere al conjunto de todas las urls
app_name = "empleado_app"

urlpatterns = [
    path(
      '',
      views.InicioView.as_view(),
      name='inicio'
    ),
    
    path(
      'listar-todo-empleados/',
      views.ListaAllEmpleados.as_view(), 
      name='empleados_all'
    ),

    path(
      'lista-by-area/<shor_name>', 
      views.ListByAreaEmpleado.as_view(),
      name='empleados_area'
    ),
    path(
      'lista-empleados-admin/',
      views.ListEmpleadosAdmin.as_view(),
      name='empleados_admin'
    ),

    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListaHabilidadesEmpleado.as_view()),
    path(
      'ver-empleado/<pk>',
      views.EmpleadoDetailView.as_view(),
      name='empleado_detail'),
      
    path(
      'add-empleado/', 
      views.EmpleadoCreateView.as_view(),
      name='empleado_add'
    ),

    path('success/', views.SuccessView.as_view(), name='correcto'),

    path(
      'update-empleado/<pk>/', 
      views.EmpleadoUpdateView.as_view(), 
      name='modificar_empledo'
    ),
    path(
      'delete-empleado/<pk>/', 
      views.EmpleadoDeleteView.as_view(), 
      name='eliminar_empleado'
    ),
]

empresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #incluir rutas empleados
    path('', include('empleados.urls')),
    path('',include('home.urls')),
    path('',include('departamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('add/', views.PruebaCreateView.as_view(), name='prueba_add'),
    path('prueba/', views.PruebaListView.as_view(), name='prueba_lista')
]

empleados/models.py
from django.db import models
#importar ckeditor
from ckeditor.fields import RichTextField # type: ignore
from departamentos.models import Departamento

# Create your models here.
class Habilidad(models.Model):
  habilidad = models.CharField('Habilidad', max_length=50)

  class Meta:
    verbose_name = "Habilidad"
    verbose_name_plural = "Habilidades Empleados"

  def __str__(self):
    return str(self.id) + '-' + self.habilidad



class Empleado(models.Model):
  """Modelo para la tabla empleado"""

  #CONTADOR
  #ADMINISTRADOR
  #ECONOMISTA
  #OTRO
  JOB_CHOICES = (
    ('0', 'CONTADOR'),
    ('1', 'ADMINISTRADOR'),
    ('2', 'ECONOMISTA'),
    ('3', 'OTRO'),
  )
  #atributos
  first_name = models.CharField('Nombre', max_length=50)
  last_name = models.CharField('Apellidos', max_length=20)
  job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
  image = models.ImageField(upload_to='empleado', blank=True, null=True)
  #creacion ForenKey
  departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
  habilidades = models.ManyToManyField(Habilidad)
  hoja_vida = RichTextField()

  def __str__(self):
    return str(self.id) + '-' + self.first_name + '-' + self.last_name

empleados/forms.py
from django import forms 

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
  class Meta:
    model = Empleado 
    fields = (
      'first_name',
      'last_name',
      'job',
      'departamento',
      'image',
      'habilidades',
    )
    widgets = {
      'habilidades': forms.CheckboxSelectMultiple()
    }

empleados/views.py
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
  TemplateView,
  ListView,
  DetailView,
  CreateView,
  UpdateView,
  DeleteView,
)

#importar el modelo Empleado
from .models import Empleado

#import forms
from .forms import EmpleadoForm

# Create your views here.
class InicioView(TemplateView):
  """ vista pagina de inicio"""
  template_name = 'inicio.html'


#1-Listar todos los empleados de la empresa
class ListaAllEmpleados(ListView):
  template_name = 'empleados/list_all.html'
  ordering = 'first_name'
  paginate_by = 6
  model = Empleado

  def get_queryset(self):
    palabra_clave = self.request.GET.get("kword", '')
    lista = Empleado.objects.filter(
      first_name__icontains=palabra_clave
    )
    return lista

#2-Listar todos los empleados que pertenecen a una area de la empresa
class ListByAreaEmpleado(ListView):
  template_name = 'empleados/list_by_area.html'
  context_object_name = 'empleados'

  def get_queryset(self):
    #el codigo que se necesita
    area = self.kwargs['shor_name']
    lista = Empleado.objects.filter(
      departamento__shor_name = area
    )
    return lista
  
class ListEmpleadosAdmin(ListView):
  template_name = 'empleados/lista_empleados.html'
  paginate_by = 5
  ordering = 'first_name'
  model = Empleado
  context_object_name = 'empleados'


#3-Listar los empleados por palabra clave (buscador: Juan)
class ListEmpleadoByKword(ListView):
  """Listar empleados por palabra clave"""
  template_name = 'empleados/by_kword.html'
  context_object_name = 'empleados'

  def get_queryset(self):
    print('''''''''''')
    palabra_clave = self.request.GET.get("kword", '')
    lista = Empleado.objects.filter(
      first_name= palabra_clave
    )
    return lista


#4-Listar habilidades de un empleado
class ListaHabilidadesEmpleado(ListView):
  template_name = 'empleados/habilidades.html'
  context_object_name = 'habilidades'

  def get_queryset(self):
    empleado = Empleado.objects.get(id=8)
    return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
  template_name = 'empleados/detail_empleados.html'
  model = Empleado

  def get_context_data(self, **kwargs):
    context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
    context['titulo'] = 'Empleado del mes'
    return context 

#create success
class SuccessView(TemplateView):
  template_name = 'empleados/success.html'

#permite crear un empleado
class EmpleadoCreateView(CreateView):
  template_name = 'empleados/add.html'
  model = Empleado
  form_class = EmpleadoForm
  success_url = reverse_lazy('empleado_app:empleados_admin')

  def form_valid(self, form):
      empleado = form.save(commit=False)
      empleado.save()
      return super(EmpleadoCreateView, self).form_valid(form)
  
#permite actualizar el empleado
class EmpleadoUpdateView(UpdateView):
  template_name = "empleados/update.html"
  model = Empleado
  fields = ['first_name', 'last_name', 'job', 'departamento', 'habilidades']
  success_url = reverse_lazy('empleado_app:empleados_admin')


  def post(self, request, *args, **kwargs):
    self.object = self.get_object()
    print("Metodo Post")
    print(request.POST)
    return super().post(request, *args, **kwargs)
  
  def form_valid(self, form):
    form
    return super(EmpleadoUpdateView, self).form_valid(form)
  
#permite eliminar empleado
class EmpleadoDeleteView(DeleteView):
  template_name = "empleados/delete.html"
  model = Empleado
  success_url = reverse_lazy('empleado_app:empleados_admin')

templates/empleados/add.html
{% extends 'base.html' %}



{% block title %}
  Registrar Empleado
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Registrar empelado</h1>
    <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}

      <div class="medium-6 cell">
        <label>Nombres:
          {{form.first_name}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Apellidos:
          {{form.last_name}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Trabajo:
          {{form.job}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Departamento:
          {{form.departamento}}
        </label>
      </div>
      <div class="medium-12 cell">
        <label>Habilidades:
          {{form.habilidades}}
        </label>
      </div>
      <div class="medium-12 cell">
        <label>foto:
          {{form.image}}
        </label>
      </div>
      <div class="medium-12 cell">
        <button type="submit" class="button success">Guardar</button>
      </div>

    </form>
  </div>

{% endblock content %}

templates/empleados/by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form method="GET">
  <input type="text" id="kword" name="kword"  placeholder="Ingrese nombre">
  <button type="submit">Buscar</button>
</form>

<h3>Lista Resultado</h3>

<ul>
  {% for e in  empleados %}
    <li>{{e}}</li>
  {% endfor %}
</ul>

  

templates/empleados/delete.html
{% extends 'base.html' %}


{% block title %}
  Eliminar Empleado
{% endblock title %}


{% block content %}
  {% include 'includes/header.html' %}

 <div class="grid-container">
   <div class="grid-x">
     <h1 class="cell">Eliminar Empelado: {{object.first_name}}</h1>

     <form class="cell" method="POST">{% csrf_token %}
       <div class="callout secondary">
         <h5>¿Desea eliminar este empleado?</h5>
         <button type="submit" class="alert button">Confirmar</button>
       </div>
     </form>
   </div>
 </div>

{% endblock content %}
  
  

templates/empleados/detail_empleados.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
  {{object.first_name}}
{% endblock title %}
  
{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x grid-margin-x align-center">
    <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
      <div class="card-divider">
        {{ empleado.get_job_display }}
      </div>
      
      {% if empleado.image %}
        <img src="{{ empleado.image.url }} ">
      {% else %}
        <img src=" {% static 'img/20.jpg' %}">
      {% endif %}
        
      <div class="card-section">
        <h4>{{empleado.first_name}}</h4>
        <p>{{empleado.last_name}}</p>
        <p>{{empleado.departamento.shor_name}}</p>
        <p><span class="label">Habilidades:</span></p>
        <ul class="vertical menu">
          {% for h in empleado.habilidades.all  %}
            <li>{{ h.habilidad }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
  
{% endblock content %}
  






<h3>Todos los datos:</h3>
<p>{{ empleado.first_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{ empleado.departamento }}</p>
<p>{{ empleado.habilidades }}</p>

templates/empleados/empleado_list.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Lista Empleados</h1>
    <div class="cell">
      <table>
        <thead>
          <tr>
            <th width="200">ID</th>
            <th>NOMBRES</th>
            <th width="150">APELLIDOS</th>
            <th width="150">DEPARTAMENTO</th>
            <th width="150">ACCION</th>
          </tr>
        </thead>
        <tbody>
          {% for e in empleados %}
          <tr>
            <td>{{ e.id }}</td>
            <td>{{e.first_name}}</td>
            <td>{{e.last_name}}</td>
            <td>{{e.departamento }}</td>
            <td>
              <a class="button success" href="{% url 'empleado_app:modificar_empledo' e.id %}">Editar</a>
            </td>
            <td>
              <a class="button alert" href="{% url 'empleado_app:eliminar_empleado' e.id %}">Eliminar</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="cell">
      {% if is_paginated %}
      <nav aria-label="Pagination">
        <ul class="pagination text-center">
          {% if page_obj.has_previous %}
          <li class="pagination-previous">
            <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
          </li>
          {% else %}
          <li class="pagination-previous disabled">Anterior</li>
          {% endif %}

          {% for pagina in paginator.page_range %}

          {% if  pagina == page_obj.number %}
          <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
          {% else %}
          <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
          {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="pagination-next">
            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
          </li>
          {% else %}
          <li class="pagination-next disabled">Siguiente</li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
  </div>
</div>

{% endblock content %}

templates/empleados/habilidades.html
<h1>Habilidades de Empleado</h1>

<ul>
  
  {% for h in  habilidades %}
    <li>{{ h }}</li>
  {% endfor %}
    
</ul>

templates/empleados/inicio.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  
</head>
<body>
  <header>
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a href="#Item-1">Item 1</a>
        <ul class="menu">
          <li><a href="#Item-1A">Item 1A</a></li>
          <li>
            <a href="#Item-1B">Item 1B</a>
            <ul class="menu">
              <li><a href="#Item-1Bi">Item 1B i</a></li>
              <li><a href="#Item-1Bii">Item 1B ii</a></li>
              <li>
                <a href="#Item-1Biii">Item 1B iii</a>
                <ul class="menu">
                  <li><a href="#Item-1Biiialpha">Item 1B iii alpha</a></li>
                  <li><a href="#Item-1Biiiomega">Item 1B iii omega</a></li>
                </ul>
              </li>
              <li>
                <a href="#Item-1Biv">Item 1B iv</a>
                <ul class="menu">
                  <li><a href="#Item-1Bivalpha">Item 1B iv alpha</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <li><a href="#Item-1C">Item 1C</a></li>
        </ul>
      </li>
      <li>
        <a href="#Item-2">Item 2</a>
        <ul class="menu">
          <li><a href="#Item-2A">Item 2A</a></li>
          <li><a href="#Item-2B">Item 2B</a></li>
        </ul>
      </li>
      <li><a href="#Item-3">Item 3</a></li>
      <li><a href="#Item-4">Item 4</a></li>
    </ul>
  </header>

  
</body>
</html>

templates/empleados/list_all.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Lista Empleados</h1>
    <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
      <div class="cell large-7">
        <input type="text" id="kword" name="kword" placeholder="buscar empleado">
      </div>
      <div class="cell large-2">
        <button type="submit" class="success button">Buscar</button>
      </div>
    </form>
    <div class="cell">
      <table>
        <thead>
          <tr>
            <th width="200">ID</th>
            <th>NOMBRES</th>
            <th width="150">APELLIDOS</th>
            <th width="150">DEPARTAMENTO</th>
            <th width="150">ACCION</th>
          </tr>
        </thead>
        <tbody>
          {%for e in object_list %}
          <tr>
            <td>{{ e.id }}</td>
            <td>{{ e.first_name }}</td>
            <td>{{ e.last_name }}</td>
            <td>{{ e.departamento }}</td>
            <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="cell">
      {% if is_paginated %}
      <nav aria-label="Pagination">
        <ul class="pagination text-center">
          {% if page_obj.has_previous %}
          <li class="pagination-previous">
            <a href="?page={{page.obj.has_previous}}">Anterior</a>
          </li>
          {% else %}
          <li class="pagination-previous disabled">Anterior</li>
          {% endif %}

          {% for pagina in paginator.page_range %}

          {% if  pagina == page_obj.number %}
          <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
          {% else %}
          <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
          {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="pagination-next">
            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
          </li>
          {% else %}
          <li class="pagination-next disabled">Siguiente</li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
    </div>
  </div>
</div>
 
{% endblock content %}
  

templates/empleados/list_by_area.html
{% extends 'base.html' %}


{% block title %}
  lista empleados por departamento
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <div class="cell">Empelados por area:</div>
    <div class="cell">
      <table>
        <thead>
          <tr>
            <th width="200">ID</th>
            <th>NOMBRES</th>
            <th width="150">APELLIDOS</th>
            <th width="150">DEPARTAMENTO</th>
            <th width="150">ACCION</th>
          </tr>
        </thead>
        <tbody>
          {% for e in empleados %}
          <tr>
            <td>{{e.id}}</td>
            <td>{{e.first_name}}</td>
            <td>{{e.last_name}}</td>
            <td>{{e.departamento}}</td>
            <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock content %}

templates/empleados/success.html
<h1>Felicitaciones, se guardo correctamente el empleado</h1>

templates/empleados/update.html
{% extends 'base.html' %}


{% block title %}
  Editar Empleado
{% endblock title %}


{% block content %}
  {% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">
      Modificar Empleado
    </h1>
    <div class="cell">
      <form class="grid-x grid-margin-x" method="POST"> {% csrf_token %}
        <div class="cell large-6">
          <label>Nombres:
            {{ form.first_name }}
          </label>
        </div>
        <div class="cell large-6">
          <label>Apellidos:
            {{ form.last_name }}
          </label>
        </div>
        <div class="cell large-6">
          <label>Trabajo:
            {{ form.job }}
          </label>
        </div>
        <div class="cell large-6">
          <label>Area:
            {{ form.departamento }}
          </label>
        </div>
        <div class="cell large-6">
          <label>Habilidades extra:
            {{ form.habilidades }}
          </label>
        </div>
        <div class="cell">
          <button type="submit" class="success button">Guardar</button>
        </div>
      </form>
    </div>
  </div>

{% endblock content %}
  