departamentos/urls.py
from django.contrib import admin
from django.urls import path

#importar las views
from . import views

app_name = "departamento_app"


urlpatterns = [
    path('departamento-lista/',
        views.DepartamentoListView.as_view(),
        name='departamento_list'
    ),

    path('new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='nuevo_departamento'
    ),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

#se refiere al conjunto de todas las urls
app_name = "empleado_app"

urlpatterns = [
    path(
      '',
      views.InicioView.as_view(),
      name='inicio'
    ),
    
    path(
      'listar-todo-empleados/',
      views.ListaAllEmpleados.as_view(), 
      name='empleados_all'
    ),

    path(
      'lista-by-area/<shor_name>', 
      views.ListByAreaEmpleado.as_view(),
      name='empleados_area'
    ),
    path(
      'lista-empleados-admin/',
      views.ListEmpleadosAdmin.as_view(),
      name='empleados_admin'
    ),

    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListaHabilidadesEmpleado.as_view()),
    path(
      'ver-empleado/<pk>',
      views.EmpleadoDetailView.as_view(),
      name='empleado_detail'),
      
    path(
      'add-empleado/', 
      views.EmpleadoCreateView.as_view(),
      name='empleado_add'
    ),

    path('success/', views.SuccessView.as_view(), name='correcto'),

    path(
      'update-empleado/<pk>/', 
      views.EmpleadoUpdateView.as_view(), 
      name='modificar_empledo'
    ),
    path(
      'delete-empleado/<pk>/', 
      views.EmpleadoDeleteView.as_view(), 
      name='eliminar_empleado'
    ),
]

empresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #incluir rutas empleados
    path('', include('empleados.urls')),
    path('',include('home.urls')),
    path('',include('departamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('add/', views.PruebaCreateView.as_view(), name='prueba_add'),
    path('prueba/', views.PruebaListView.as_view(), name='prueba_lista')
]

templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a class="menu-text" href="{% url 'empleado_app:inicio' %}">Empelados</a>
      </li>
      <li>
        <a href=" {% url 'empleado_app:empleados_all' %} ">Listar</a>
      </li>
      <li>
        <a href="{% url 'departamento_app:departamento_list' %}">Departamentos</a>
      </li>
      <li><a href="{% url 'empleado_app:empleados_admin' %}">Administrar</a></li>
      <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar empleado"></li>
      <li><a href="{% url 'empleado_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
    </ul>
  </div>
</div>