departamentos/urls.py
from django.contrib import admin
from django.urls import path

#importar las views
from . import views

app_name = "departamento_app"


urlpatterns = [
    path('departamento-lista/',
        views.DepartamentoListView.as_view(),
        name='departamento_list'
    ),

    path('new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='nuevo_departamento'
    ),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

#se refiere al conjunto de todas las urls
app_name = "empleado_app"

urlpatterns = [
    path(
      '',
      views.InicioView.as_view(),
      name='inicio'
    ),
    
    path(
      'listar-todo-empleados/',
      views.ListaAllEmpleados.as_view(), 
      name='empleados_all'
    ),

    path(
      'lista-by-area/<shor_name>', 
      views.ListByAreaEmpleado.as_view(),
      name='empleados_area'
    ),
    path(
      'lista-empleados-admin/',
      views.ListEmpleadosAdmin.as_view(),
      name='empleados_admin'
    ),

    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListaHabilidadesEmpleado.as_view()),
    path(
      'ver-empleado/<pk>',
      views.EmpleadoDetailView.as_view(),
      name='empleado_detail'),
      
    path(
      'add-empleado/', 
      views.EmpleadoCreateView.as_view(),
      name='empleado_add'
    ),

    path('success/', views.SuccessView.as_view(), name='correcto'),

    path(
      'update-empleado/<pk>/', 
      views.EmpleadoUpdateView.as_view(), 
      name='modificar_empledo'
    ),
    path(
      'delete-empleado/<pk>/', 
      views.EmpleadoDeleteView.as_view(), 
      name='eliminar_empleado'
    ),
]

empresa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #incluir rutas empleados
    path('', include('empleados.urls')),
    path('',include('home.urls')),
    path('',include('departamentos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('add/', views.PruebaCreateView.as_view(), name='prueba_add'),
    path('prueba/', views.PruebaListView.as_view(), name='prueba_lista')
]

departamentos/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
  name = models.CharField('Nombre', max_length=50)
  shor_name = models.CharField('Nombre Corto', max_length=20, unique=True)
  anulate = models.BooleanField('Anulado', default=False)

  class Meta:
    verbose_name = "Mi Departamento"
    verbose_name_plural = "Areas de la Empresa"
    ordering = ['-name']

  def __str__(self):
    return str(self.id) + '-' + self.name + '-' + self.shor_name

departamentos/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
  nombre = forms.CharField(max_length=50)
  apellidos = forms.CharField(max_length=50)
  departamento = forms.CharField(max_length=50)
  shorname = forms.CharField(max_length=20)

departamentos/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView

#importar el modelo Deparatamento
from .models import Departamento
from empleados.models import Empleado 
#import el form
from .forms import NewDepartamentoForm 

# Create your views here.
class DepartamentoListView(ListView):
  template_name = 'departamento/lista.html'
  model = Departamento
  context_object_name = 'departamentos'


class NewDepartamentoView(FormView):
  template_name = 'departamento/new_departamento.html'
  form_class = NewDepartamentoForm
  success_url = '/'

  def form_valid(self, form):
    print("estamos en el form valid*******")

    depa = Departamento(
      name = form.cleaned_data['departamento'],
      shor_name = form.cleaned_data['shorname'],
    )
    depa.save()

    nombre = form.cleaned_data['nombre']
    apellido = form.cleaned_data['apellidos']
    Empleado.objects.create(
      first_name=nombre,
      last_name= apellido,
      job='1',
      departamento=depa
    )
    return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
  Lista Departamentos
{% endblock title %}


{% block content %}
  {% include 'includes/header.html' %}

  <div class="grid-container">
    <div class="grid-x">
      <h1 class="cell">Lista Departamento</h1>
      <div class="cell">
        <table>
          <tbody>
            {% for d in departamentos  %}
            <tr>
              <td>{{d.name}}</td>
              <td>{{d.shor_name}}</td>
              <td>
                <a class="button warning"
                  href="{% url 'empleado_app:empleados_area' d.shor_name %}">Ver
                  Empleados</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

  </div

{% endblock content %}
  

templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
  Registrar Departamento
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Regitrar Departamento</h1>
    <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
      <div class="medium-6 cell">
        <label>Nombres:
          {{form.nombre}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>apellidos
          {{form.apellidos}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>departamento
          {{form.departamento}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>shorname
          {{form.shorname}}
        </label>
      </div>
      <div class="medium-12 cell">
        <button type="submit" class="button">Guardar</button>
      </div>
    </form>
  </div>
</div>

{% endblock content %}
  